#### application-dev.yml
server:
  port: 8004

spring:
  # 开发环境配置
  profiles: dev

  # cloud 配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 199037wW@

  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 199037wW@
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  # mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # locations 当前类路径#locations 当前类路径
  mapper-locations: classpath:com/atguigu/educms/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

