#### application-dev.yml
server:
  port: 8003

spring:
  # 开发环境配置
  profiles: test

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB


# 阿里云服务配置测试集成
aliyun:
  vod:
    file:
      keyid: 你的keyid
      keysecret: 你的keysecret

