#### application-dev.yml
#服务端口
server:
  port: 8002

# nacos服务地址
spring:
  # 开发环境配置
  profiles: test

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 阿里云服务配置
aliyun:
  oss:
    file:
      endpoint: 服务器位置，例如oss-cn-beijing.aliyuncs.com
      keyid: 你的keyid
      keysecret: 你的keysecret
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: 你的bucketname，例如tec-file
